version: '3.9'
services:
  web:
    build: .
    ports:
      - '3001:3001'
    volumes:
      - './storage:/app/storage'
    command: sh -c 'test -f storage/boochat.db || (yarn prisma db push; yarn prisma db seed --preview-feature); node build'
    restart: unless-stopped
